export const irregularVerbs = [
  {
    verb: "arise",
    2: "arose",
    3: "arisen",
    meaningSP: "levantarse",
    meaningPR: "levantarse",
    meaningCH: "升起",
  },
  {
    verb: "awake",
    2: "awoke",
    3: "awoken",
    meaningSP: "despertarse",
    meaningPR: "despertarse",
    meaningCH: "醒来",
  },
  {
    verb: "be",
    2: "was/were",
    3: "been",
    meaningSP: "ser/estar",
    meaningPR: "ser/estar",
    meaningCH: "是/在",
  },
  {
    verb: "beat",
    2: "beat",
    3: "beaten",
    meaningSP: "derrotar",
    meaningPR: "derrotar",
    meaningCH: "击败",
  },
  {
    verb: "become",
    2: "became",
    3: "become",
    meaningSP: "convertirse",
    meaningPR: "convertirse",
    meaningCH: "变成",
  },
  {
    verb: "begin",
    2: "began",
    3: "begun",
    meaningSP: "comenzar",
    meaningPR: "comenzar",
    meaningCH: "开始",
  },
  {
    verb: "bet",
    2: "bet",
    3: "bet",
    meaningSP: "apostar",
    meaningPR: "apostar",
    meaningCH: "打赌",
  },
  {
    verb: "bid",
    2: "bid",
    3: "bid",
    meaningSP: "pujar",
    meaningPR: "pujar",
    meaningCH: "出价",
  },
  {
    verb: "bind",
    2: "bound",
    3: "bound",
    meaningSP: "obligar",
    meaningPR: "obligar",
    meaningCH: "捆绑",
  },
  {
    verb: "bite",
    2: "bit",
    3: "bitten",
    meaningSP: "morder",
    meaningPR: "morder",
    meaningCH: "咬",
  },
  {
    verb: "bleed",
    2: "bled",
    3: "bled",
    meaningSP: "sangrar",
    meaningPR: "sangrar",
    meaningCH: "流血",
  },
  {
    verb: "blow",
    2: "blew",
    3: "blown",
    meaningSP: "soplar",
    meaningPR: "soplar",
    meaningCH: "吹",
  },
  {
    verb: "break",
    2: "broke",
    3: "broken",
    meaningSP: "romper",
    meaningPR: "romper",
    meaningCH: "打破",
  },
  {
    verb: "bring",
    2: "brought",
    3: "brought",
    meaningSP: "traer",
    meaningPR: "traer",
    meaningCH: "带来",
  },
  {
    verb: "build",
    2: "built",
    3: "built",
    meaningSP: "construir",
    meaningPR: "construir",
    meaningCH: "建造",
  },
  {
    verb: "burn",
    2: "burnt",
    3: "burnt",
    meaningSP: "quemar",
    meaningPR: "quemar",
    meaningCH: "燃烧",
  },
  {
    verb: "buy",
    2: "bought",
    3: "bought",
    meaningSP: "comprar",
    meaningPR: "comprar",
    meaningCH: "购买",
  },
  {
    verb: "catch",
    2: "caught",
    3: "caught",
    meaningSP: "atrapar",
    meaningPR: "atrapar",
    meaningCH: "捕捉",
  },
  {
    verb: "choose",
    2: "chose",
    3: "chosen",
    meaningSP: "elegir",
    meaningPR: "elegir",
    meaningCH: "选择",
  },
  {
    verb: "come",
    2: "came",
    3: "come",
    meaningSP: "venir",
    meaningPR: "venir",
    meaningCH: "来",
  },
  {
    verb: "cost",
    2: "cost",
    3: "cost",
    meaningSP: "costar",
    meaningPR: "costar",
    meaningCH: "花费",
  },
  {
    verb: "cut",
    2: "cut",
    3: "cut",
    meaningSP: "cortar",
    meaningPR: "cortar",
    meaningCH: "切割",
  },
  {
    verb: "dare",
    2: "dared",
    3: "dared",
    meaningSP: "atreverse",
    meaningPR: "atreverse",
    meaningCH: "敢",
  },
  {
    verb: "deal",
    2: "dealt",
    3: "dealt",
    meaningSP: "tratar",
    meaningPR: "tratar",
    meaningCH: "处理",
  },
  {
    verb: "dig",
    2: "dug",
    3: "dug",
    meaningSP: "cavar",
    meaningPR: "cavar",
    meaningCH: "挖",
  },
  {
    verb: "do",
    2: "did",
    3: "done",
    meaningSP: "hacer",
    meaningPR: "hacer",
    meaningCH: "做",
  },
  {
    verb: "draw",
    2: "drew",
    3: "drawn",
    meaningSP: "dibujar",
    meaningPR: "dibujar",
    meaningCH: "画",
  },
  {
    verb: "drink",
    2: "drank",
    3: "drunk",
    meaningSP: "beber",
    meaningPR: "beber",
    meaningCH: "喝",
  },
  {
    verb: "drive",
    2: "drove",
    3: "driven",
    meaningSP: "conducir",
    meaningPR: "conducir",
    meaningCH: "驾驶",
  },
  {
    verb: "eat",
    2: "ate",
    3: "eaten",
    meaningSP: "comer",
    meaningPR: "comer",
    meaningCH: "吃",
  },
  {
    verb: "fall",
    2: "fell",
    3: "fallen",
    meaningSP: "caer",
    meaningPR: "caer",
    meaningCH: "摔倒",
  },
  {
    verb: "feed",
    2: "fed",
    3: "fed",
    meaningSP: "alimentar",
    meaningPR: "alimentar",
    meaningCH: "喂养",
  },
  {
    verb: "feel",
    2: "felt",
    3: "felt",
    meaningSP: "sentir",
    meaningPR: "sentir",
    meaningCH: "感觉",
  },
  {
    verb: "fight",
    2: "fought",
    3: "fought",
    meaningSP: "luchar",
    meaningPR: "luchar",
    meaningCH: "打斗",
  },
  {
    verb: "find",
    2: "found",
    3: "found",
    meaningSP: "encontrar",
    meaningPR: "encontrar",
    meaningCH: "找到",
  },
  {
    verb: "fly",
    2: "flew",
    3: "flown",
    meaningSP: "volar",
    meaningPR: "volar",
    meaningCH: "飞",
  },
  {
    verb: "forbid",
    2: "forbade",
    3: "forbidden",
    meaningSP: "prohibir",
    meaningPR: "prohibir",
    meaningCH: "禁止",
  },
  {
    verb: "forget",
    2: "forgot",
    3: "forgotten",
    meaningSP: "olvidar",
    meaningPR: "olvidar",
    meaningCH: "忘记",
  },
  {
    verb: "forgive",
    2: "forgave",
    3: "forgiven",
    meaningSP: "perdonar",
    meaningPR: "perdonar",
    meaningCH: "原谅",
  },
  {
    verb: "get",
    2: "got",
    3: "gotten",
    meaningSP: "obtener",
    meaningPR: "obtener",
    meaningCH: "得到",
  },
  {
    verb: "give",
    2: "gave",
    3: "given",
    meaningSP: "dar",
    meaningPR: "dar",
    meaningCH: "给",
  },
  {
    verb: "go",
    2: "went",
    3: "gone",
    meaningSP: "ir",
    meaningPR: "ir",
    meaningCH: "去",
  },
  {
    verb: "grow",
    2: "grew",
    3: "grown",
    meaningSP: "crecer",
    meaningPR: "crecer",
    meaningCH: "成长",
  },
  {
    verb: "hang",
    2: "hung",
    3: "hung",
    meaningSP: "colgar",
    meaningPR: "colgar",
    meaningCH: "悬挂",
  },
  {
    verb: "have",
    2: "had",
    3: "had",
    meaningSP: "tener",
    meaningPR: "tener",
    meaningCH: "有",
  },
  {
    verb: "hear",
    2: "heard",
    3: "heard",
    meaningSP: "escuchar",
    meaningPR: "escuchar",
    meaningCH: "听",
  },
  {
    verb: "hide",
    2: "hid",
    3: "hidden",
    meaningSP: "esconder",
    meaningPR: "esconder",
    meaningCH: "隐藏",
  },
  {
    verb: "hit",
    2: "hit",
    3: "hit",
    meaningSP: "golpear",
    meaningPR: "golpear",
    meaningCH: "打",
  },
  {
    verb: "hold",
    2: "held",
    3: "held",
    meaningSP: "sostener",
    meaningPR: "sostener",
    meaningCH: "持有",
  },
  {
    verb: "hurt",
    2: "hurt",
    3: "hurt",
    meaningSP: "herir",
    meaningPR: "herir",
    meaningCH: "伤害",
  },
  {
    verb: "keep",
    2: "kept",
    3: "kept",
    meaningSP: "mantener",
    meaningPR: "mantener",
    meaningCH: "保持",
  },
  {
    verb: "know",
    2: "knew",
    3: "known",
    meaningSP: "saber",
    meaningPR: "saber",
    meaningCH: "知道",
  },
  {
    verb: "lead",
    2: "led",
    3: "led",
    meaningSP: "liderar",
    meaningPR: "liderar",
    meaningCH: "领导",
  },
  {
    verb: "leave",
    2: "left",
    3: "left",
    meaningSP: "dejar",
    meaningPR: "dejar",
    meaningCH: "离开",
  },
  {
    verb: "lend",
    2: "lent",
    3: "lent",
    meaningSP: "prestar",
    meaningPR: "prestar",
    meaningCH: "借",
  },
  {
    verb: "let",
    2: "let",
    3: "let",
    meaningSP: "dejar",
    meaningPR: "dejar",
    meaningCH: "允许",
  },
  {
    verb: "lie",
    2: "lay",
    3: "lain",
    meaningSP: "mentir",
    meaningPR: "mentir",
    meaningCH: "说谎",
  },
  {
    verb: "light",
    2: "lit",
    3: "lit",
    meaningSP: "encender",
    meaningPR: "encender",
    meaningCH: "点燃",
  },
  {
    verb: "lose",
    2: "lost",
    3: "lost",
    meaningSP: "perder",
    meaningPR: "perder",
    meaningCH: "丢失",
  },
  {
    verb: "make",
    2: "made",
    3: "made",
    meaningSP: "hacer",
    meaningPR: "hacer",
    meaningCH: "制造",
  },
  {
    verb: "mean",
    2: "meant",
    3: "meant",
    meaningSP: "significar",
    meaningPR: "significar",
    meaningCH: "意味着",
  },
  {
    verb: "meet",
    2: "met",
    3: "met",
    meaningSP: "conocer",
    meaningPR: "conocer",
    meaningCH: "见面",
  },
  {
    verb: "pay",
    2: "paid",
    3: "paid",
    meaningSP: "pagar",
    meaningPR: "pagar",
    meaningCH: "付款",
  },
  {
    verb: "put",
    2: "put",
    3: "put",
    meaningSP: "poner",
    meaningPR: "poner",
    meaningCH: "放置",
  },
  {
    verb: "read",
    2: "read",
    3: "read",
    meaningSP: "leer",
    meaningPR: "leer",
    meaningCH: "读",
  },
  {
    verb: "ride",
    2: "rode",
    3: "ridden",
    meaningSP: "montar",
    meaningPR: "montar",
    meaningCH: "骑",
  },
  {
    verb: "run",
    2: "ran",
    3: "run",
    meaningSP: "correr",
    meaningPR: "correr",
    meaningCH: "跑",
  },
  {
    verb: "see",
    2: "saw",
    3: "seen",
    meaningSP: "ver",
    meaningPR: "ver",
    meaningCH: "看见",
  },
  {
    verb: "sell",
    2: "sold",
    3: "sold",
    meaningSP: "vender",
    meaningPR: "vender",
    meaningCH: "卖",
  },
  {
    verb: "send",
    2: "sent",
    3: "sent",
    meaningSP: "enviar",
    meaningPR: "enviar",
    meaningCH: "发送",
  },
  {
    verb: "set",
    2: "set",
    3: "set",
    meaningSP: "establecer",
    meaningPR: "establecer",
    meaningCH: "设置",
  },
  {
    verb: "shine",
    2: "shone",
    3: "shone",
    meaningSP: "brillar",
    meaningPR: "brillar",
    meaningCH: "发光",
  },
  {
    verb: "shoot",
    2: "shot",
    3: "shot",
    meaningSP: "disparar",
    meaningPR: "disparar",
    meaningCH: "射击",
  },
  {
    verb: "show",
    2: "showed",
    3: "shown",
    meaningSP: "mostrar",
    meaningPR: "mostrar",
    meaningCH: "展示",
  },
  {
    verb: "sing",
    2: "sang",
    3: "sung",
    meaningSP: "cantar",
    meaningPR: "cantar",
    meaningCH: "唱歌",
  },
  {
    verb: "sit",
    2: "sat",
    3: "sat",
    meaningSP: "sentarse",
    meaningPR: "sentarse",
    meaningCH: "坐",
  },
  {
    verb: "sleep",
    2: "slept",
    3: "slept",
    meaningSP: "dormir",
    meaningPR: "dormir",
    meaningCH: "睡觉",
  },
  {
    verb: "speak",
    2: "spoke",
    3: "spoken",
    meaningSP: "hablar",
    meaningPR: "hablar",
    meaningCH: "说话",
  },
  {
    verb: "spend",
    2: "spent",
    3: "spent",
    meaningSP: "gastar",
    meaningPR: "gastar",
    meaningCH: "花费",
  },
  {
    verb: "stand",
    2: "stood",
    3: "stood",
    meaningSP: "estar de pie",
    meaningPR: "estar de pie",
    meaningCH: "站立",
  },
  {
    verb: "steal",
    2: "stole",
    3: "stolen",
    meaningSP: "robar",
    meaningPR: "robar",
    meaningCH: "偷",
  },
  {
    verb: "stick",
    2: "stuck",
    3: "stuck",
    meaningSP: "pegar",
    meaningPR: "pegar",
    meaningCH: "粘贴",
  },
  {
    verb: "strike",
    2: "struck",
    3: "struck",
    meaningSP: "golpear",
    meaningPR: "golpear",
    meaningCH: "打击",
  },
  {
    verb: "swim",
    2: "swam",
    3: "swum",
    meaningSP: "nadar",
    meaningPR: "nadar",
    meaningCH: "游泳",
  },
  {
    verb: "take",
    2: "took",
    3: "taken",
    meaningSP: "tomar",
    meaningPR: "tomar",
    meaningCH: "拿",
  },
  {
    verb: "teach",
    2: "taught",
    3: "taught",
    meaningSP: "enseñar",
    meaningPR: "enseñar",
    meaningCH: "教",
  },
  {
    verb: "tell",
    2: "told",
    3: "told",
    meaningSP: "contar",
    meaningPR: "contar",
    meaningCH: "告诉",
  },
  {
    verb: "think",
    2: "thought",
    3: "thought",
    meaningSP: "pensar",
    meaningPR: "pensar",
    meaningCH: "思考",
  },
  {
    verb: "throw",
    2: "threw",
    3: "thrown",
    meaningSP: "lanzar",
    meaningPR: "lanzar",
    meaningCH: "扔",
  },
  {
    verb: "understand",
    2: "understood",
    3: "understood",
    meaningSP: "entender",
    meaningPR: "entender",
    meaningCH: "理解",
  },
  {
    verb: "wake",
    2: "woke",
    3: "woken",
    meaningSP: "despertar",
    meaningPR: "despertar",
    meaningCH: "唤醒",
  },
  {
    verb: "wear",
    2: "wore",
    3: "worn",
    meaningSP: "vestir",
    meaningPR: "vestir",
    meaningCH: "穿",
  },
  {
    verb: "win",
    2: "won",
    3: "won",
    meaningSP: "ganar",
    meaningPR: "ganar",
    meaningCH: "赢",
  },
];
