export const irregularVerbs = [
  {
    verb: "arise",
    2: "arose",
    3: "arisen",
    meaning: "levantarse",
    meaningPR: "erguer-se",
  },
  {
    verb: "awake",
    2: "awoke",
    3: "awoken",
    meaning: "despertarse",
    meaningPR: "despertar",
  },
  {
    verb: "be",
    2: "was/were",
    3: "been",
    meaning: "ser/estar",
    meaningPR: "ser/estar",
  },
  {
    verb: "beat",
    2: "beat",
    3: "beaten",
    meaning: "derrotar",
    meaningPR: "derrotar",
  },
  {
    verb: "become",
    2: "became",
    3: "become",
    meaning: "convertirse",
    meaningPR: "tornar-se",
  },
  {
    verb: "begin",
    2: "began",
    3: "begun",
    meaning: "comenzar",
    meaningPR: "começar",
  },
  {
    verb: "bet",
    2: "bet",
    3: "bet",
    meaning: "apostar",
    meaningPR: "apostar",
  },
  {
    verb: "bid",
    2: "bid",
    3: "bid",
    meaning: "pujar",
    meaningPR: "fazer um lance",
  },
  {
    verb: "bind",
    2: "bound",
    3: "bound",
    meaning: "obligar",
    meaningPR: "amarrar",
  },
  {
    verb: "bite",
    2: "bit",
    3: "bitten",
    meaning: "morder",
    meaningPR: "morder",
  },
  {
    verb: "bleed",
    2: "bled",
    3: "bled",
    meaning: "sangrar",
    meaningPR: "sangrar",
  },
  {
    verb: "blow",
    2: "blew",
    3: "blown",
    meaning: "soplar",
    meaningPR: "soprar",
  },
  {
    verb: "break",
    2: "broke",
    3: "broken",
    meaning: "romper",
    meaningPR: "quebrar",
  },
  {
    verb: "bring",
    2: "brought",
    3: "brought",
    meaning: "traer",
    meaningPR: "trazer",
  },
  {
    verb: "build",
    2: "built",
    3: "built",
    meaning: "construir",
    meaningPR: "construir",
  },
  {
    verb: "burn",
    2: "burnt",
    3: "burnt",
    meaning: "quemar",
    meaningPR: "queimar",
  },
  {
    verb: "buy",
    2: "bought",
    3: "bought",
    meaning: "comprar",
    meaningPR: "comprar",
  },
  {
    verb: "catch",
    2: "caught",
    3: "caught",
    meaning: "atrapar",
    meaningPR: "pegar",
  },
  {
    verb: "choose",
    2: "chose",
    3: "chosen",
    meaning: "elegir",
    meaningPR: "escolher",
  },
  {
    verb: "come",
    2: "came",
    3: "come",
    meaning: "venir",
    meaningPR: "vir",
  },
  {
    verb: "cost",
    2: "cost",
    3: "cost",
    meaning: "costar",
    meaningPR: "custar",
  },
  {
    verb: "cut",
    2: "cut",
    3: "cut",
    meaning: "cortar",
    meaningPR: "cortar",
  },
  {
    verb: "dare",
    2: "dared",
    3: "dared",
    meaning: "atreverse",
    meaningPR: "ousar",
  },
  {
    verb: "deal",
    2: "dealt",
    3: "dealt",
    meaning: "tratar",
    meaningPR: "lidar",
  },
  {
    verb: "dig",
    2: "dug",
    3: "dug",
    meaning: "cavar",
    meaningPR: "cavar",
  },
  {
    verb: "do",
    2: "did",
    3: "done",
    meaning: "hacer",
    meaningPR: "fazer",
  },
  {
    verb: "draw",
    2: "drew",
    3: "drawn",
    meaning: "dibujar",
    meaningPR: "desenhar",
  },
  {
    verb: "drink",
    2: "drank",
    3: "drunk",
    meaning: "beber",
    meaningPR: "beber",
  },
  {
    verb: "drive",
    2: "drove",
    3: "driven",
    meaning: "conducir",
    meaningPR: "dirigir",
  },
  {
    verb: "eat",
    2: "ate",
    3: "eaten",
    meaning: "comer",
    meaningPR: "comer",
  },
  {
    verb: "fall",
    2: "fell",
    3: "fallen",
    meaning: "caer",
    meaningPR: "cair",
  },
  {
    verb: "feed",
    2: "fed",
    3: "fed",
    meaning: "alimentar",
    meaningPR: "alimentar",
  },
  {
    verb: "feel",
    2: "felt",
    3: "felt",
    meaning: "sentir",
    meaningPR: "sentir",
  },
  {
    verb: "fight",
    2: "fought",
    3: "fought",
    meaning: "luchar",
    meaningPR: "lutar",
  },
  {
    verb: "find",
    2: "found",
    3: "found",
    meaning: "encontrar",
    meaningPR: "encontrar",
  },
  {
    verb: "fly",
    2: "flew",
    3: "flown",
    meaning: "volar",
    meaningPR: "voar",
  },
  {
    verb: "forbid",
    2: "forbade",
    3: "forbidden",
    meaning: "prohibir",
    meaningPR: "proibir",
  },
  {
    verb: "forget",
    2: "forgot",
    3: "forgotten",
    meaning: "olvidar",
    meaningPR: "esquecer",
  },
  {
    verb: "forgive",
    2: "forgave",
    3: "forgiven",
    meaning: "perdonar",
    meaningPR: "perdoar",
  },
  {
    verb: "get",
    2: "got",
    3: "gotten",
    meaning: "obtener",
    meaningPR: "obter",
  },
  {
    verb: "give",
    2: "gave",
    3: "given",
    meaning: "dar",
    meaningPR: "dar",
  },
  {
    verb: "go",
    2: "went",
    3: "gone",
    meaning: "ir",
    meaningPR: "ir",
  },
  {
    verb: "grow",
    2: "grew",
    3: "grown",
    meaning: "crecer",
    meaningPR: "crescer",
  },
  {
    verb: "hang",
    2: "hung",
    3: "hung",
    meaning: "colgar",
    meaningPR: "pendurar",
  },
  {
    verb: "have",
    2: "had",
    3: "had",
    meaning: "tener",
    meaningPR: "ter",
  },
  {
    verb: "hear",
    2: "heard",
    3: "heard",
    meaning: "escuchar",
    meaningPR: "ouvir",
  },
  {
    verb: "hide",
    2: "hid",
    3: "hidden",
    meaning: "esconder",
    meaningPR: "esconder",
  },
  {
    verb: "hit",
    2: "hit",
    3: "hit",
    meaning: "golpear",
    meaningPR: "golpear",
  },
  {
    verb: "hold",
    2: "held",
    3: "held",
    meaning: "sostener",
    meaningPR: "segurar",
  },
  {
    verb: "hurt",
    2: "hurt",
    3: "hurt",
    meaning: "herir",
    meaningPR: "machucar",
  },
  {
    verb: "keep",
    2: "kept",
    3: "kept",
    meaning: "mantener",
    meaningPR: "manter",
  },
  {
    verb: "know",
    2: "knew",
    3: "known",
    meaning: "saber",
    meaningPR: "saber",
  },
  {
    verb: "lead",
    2: "led",
    3: "led",
    meaning: "liderar",
    meaningPR: "liderar",
  },
  {
    verb: "leave",
    2: "left",
    3: "left",
    meaning: "dejar",
    meaningPR: "deixar",
  },
  {
    verb: "lend",
    2: "lent",
    3: "lent",
    meaning: "prestar",
    meaningPR: "emprestar",
  },
  {
    verb: "let",
    2: "let",
    3: "let",
    meaning: "dejar",
    meaningPR: "deixar",
  },
  {
    verb: "lie",
    2: "lay",
    3: "lain",
    meaning: "mentir",
    meaningPR: "mentir",
  },
  {
    verb: "light",
    2: "lit",
    3: "lit",
    meaning: "encender",
    meaningPR: "acender",
  },
  {
    verb: "lose",
    2: "lost",
    3: "lost",
    meaning: "perder",
    meaningPR: "perder",
  },
  {
    verb: "make",
    2: "made",
    3: "made",
    meaning: "hacer",
    meaningPR: "fazer",
  },
  {
    verb: "mean",
    2: "meant",
    3: "meant",
    meaning: "significar",
    meaningPR: "significar",
  },
  {
    verb: "meet",
    2: "met",
    3: "met",
    meaning: "conocer",
    meaningPR: "encontrar",
  },
  {
    verb: "pay",
    2: "paid",
    3: "paid",
    meaning: "pagar",
    meaningPR: "pagar",
  },
  {
    verb: "put",
    2: "put",
    3: "put",
    meaning: "poner",
    meaningPR: "colocar",
  },
  {
    verb: "read",
    2: "read",
    3: "read",
    meaning: "leer",
    meaningPR: "ler",
  },
  {
    verb: "ride",
    2: "rode",
    3: "ridden",
    meaning: "montar",
    meaningPR: "montar",
  },
  {
    verb: "run",
    2: "ran",
    3: "run",
    meaning: "correr",
    meaningPR: "correr",
  },
  {
    verb: "see",
    2: "saw",
    3: "seen",
    meaning: "ver",
    meaningPR: "ver",
  },
  {
    verb: "sell",
    2: "sold",
    3: "sold",
    meaning: "vender",
    meaningPR: "vender",
  },
  {
    verb: "send",
    2: "sent",
    3: "sent",
    meaning: "enviar",
    meaningPR: "enviar",
  },
  {
    verb: "set",
    2: "set",
    3: "set",
    meaning: "establecer",
    meaningPR: "definir",
  },
  {
    verb: "shine",
    2: "shone",
    3: "shone",
    meaning: "brillar",
    meaningPR: "brilhar",
  },
  {
    verb: "shoot",
    2: "shot",
    3: "shot",
    meaning: "disparar",
    meaningPR: "atirar",
  },
  {
    verb: "show",
    2: "showed",
    3: "shown",
    meaning: "mostrar",
    meaningPR: "mostrar",
  },
  {
    verb: "sing",
    2: "sang",
    3: "sung",
    meaning: "cantar",
    meaningPR: "cantar",
  },
  {
    verb: "sit",
    2: "sat",
    3: "sat",
    meaning: "sentarse",
    meaningPR: "sentar",
  },
  {
    verb: "sleep",
    2: "slept",
    3: "slept",
    meaning: "dormir",
    meaningPR: "dormir",
  },
  {
    verb: "speak",
    2: "spoke",
    3: "spoken",
    meaning: "hablar",
    meaningPR: "falar",
  },
  {
    verb: "spend",
    2: "spent",
    3: "spent",
    meaning: "gastar",
    meaningPR: "gastar",
  },
  {
    verb: "stand",
    2: "stood",
    3: "stood",
    meaning: "estar de pie",
    meaningPR: "ficar de pé",
  },
  {
    verb: "steal",
    2: "stole",
    3: "stolen",
    meaning: "robar",
    meaningPR: "roubar",
  },
  {
    verb: "stick",
    2: "stuck",
    3: "stuck",
    meaning: "pegar",
    meaningPR: "colar",
  },
  {
    verb: "strike",
    2: "struck",
    3: "struck",
    meaning: "golpear",
    meaningPR: "atingir",
  },
  {
    verb: "swim",
    2: "swam",
    3: "swum",
    meaning: "nadar",
    meaningPR: "nadar",
  },
  {
    verb: "take",
    2: "took",
    3: "taken",
    meaning: "tomar",
    meaningPR: "pegar",
  },
  {
    verb: "teach",
    2: "taught",
    3: "taught",
    meaning: "enseñar",
    meaningPR: "ensinar",
  },
  {
    verb: "tell",
    2: "told",
    3: "told",
    meaning: "contar",
    meaningPR: "contar",
  },
  {
    verb: "think",
    2: "thought",
    3: "thought",
    meaning: "pensar",
    meaningPR: "pensar",
  },
  {
    verb: "throw",
    2: "threw",
    3: "thrown",
    meaning: "lanzar",
    meaningPR: "lançar",
  },
  {
    verb: "understand",
    2: "understood",
    3: "understood",
    meaning: "entender",
    meaningPR: "entender",
  },
  {
    verb: "wake",
    2: "woke",
    3: "woken",
    meaning: "despertar",
    meaningPR: "acordar",
  },
  {
    verb: "wear",
    2: "wore",
    3: "worn",
    meaning: "vestir",
    meaningPR: "vestir",
  },
  {
    verb: "win",
    2: "won",
    3: "won",
    meaning: "ganar",
    meaningPR: "ganhar",
  },
  {
    verb: "write",
    2: "wrote",
    3: "written",
    meaning: "escribir",
    meaningPR: "escrever",
  },
];
